### ISSUE TITLE
Math Matrix Component

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/components#1]
The exemple in the documentation of Math Matrix Component give a sandbox error when validating.

**Comment by mciissee** [comment]
This is an error on the doc the property 'value' does not exist.
You should replace **grade = (100, component.value);** with **grade = (100, component.matrix);**

**Comment by nimdanor** [comment]
so where is the doc that i can change it ;).

**Comment by mciissee** [comment]
This is not possible for some reason : 

1- Changing the doc required some knowledge of angular architecture because the doc is automatically generated from the source code

2- Even if you could change the doc and even if this is a project separated to the premierlangage server, the release cycle of the project is linked to pl release cycle .

**Comment by nimdanor** [comment]
ok so the bug reports goes to you in project component ?

**Comment by mciissee** [comment]
yes
