### ISSUE TITLE
Input and its value attribute

### ISSUE THREAD

**Issue by oobouillot** [PremierLangage/components#10]
If nothing has been written by the student, an input component hasn't got yet an attribute value. When something has been written (possibly, has also been deleted after), this attribute has been created.

Would it be possible to always have this attribute?

I think it would be easier to test if something is available in the answer zone of the component...

**Comment by mciissee** [comment]
The current behavior of the Input Component is to return `null` to the evaluator if the input box content is empty.

Since `null` is not a serializable JSON value it cannot be sent to the evaluator when so valid your exercise. So during the deserialization of the component missing attributes are not checked since it will imply to check it for each component that accept null attributes.

As explained in the documentation a component is the instance of a class inside grader and builder keys. So if you try to access to an undefined attribute it will raise an exception.

But since all the components extends a base class `Component` which overrides `__contains__` operator so you can check by yourself if an attribute is set or not for the component by using `in` operator.

You can find the python source code of the components by opening the file located at lib/components/components.py or by downloading the environment to open the content of the file components.py.

I created a modified version of your file `Types_et_operations.pl` in the same directory inside the editor with a valid code.

**Comment by mciissee** [comment]
duplicated issue see #9
