### ISSUE TITLE
New components : Speech recognition / Vocal synthesis

### ISSUE THREAD

**Issue by ddoyen** [PremierLangage/components#34]
Is it possible ? It would be great for language exercises.

**Comment by ddoyen** [comment]
Actually, we would just need :
- an audio player component,
- an audio recorder component.

The generation/processing of audio files would be done in Python on the server side.

**Comment by mciissee** [comment]
I cannot implement speech recognition because the API is not a standard of HTML 5 only two browsers support the API currently.

Another issue is that the API requires  permissions from the student (microphone...) that he will not necessarily accept. A component should work everywhere in every case.

For the video and audio HTML 5 comes with native components and api (very simple to use and well documented). There is no need to create these types of components.

**Comment by ddoyen** [comment]
I don't think it's a problem to ask for permission. I thought to something like that for the audio recorder : https://www.lelivrescolaire.fr/labo-langues

For the audio player, you're right : the HTML audio element will do the job. If we want a fanciest standard audio player in PL (the default player is a bit dull), can it be done simply with a CSS class ?

**Comment by mciissee** [comment]
Provide a component to only record an audio is not necessary. Also I don't know what is the lib behind the widget of "lelivrescolaire" but in any case the widget use the browser speech recognition API which is not cross-platform as I said. This type of widget is not intended to be a component.

For the audio element, yes you can create your own css to customize it. I cannot create a component only to modify the default css of a native element because this will increase the loading time of the exercise since unused css will be loaded. A component should be a complex widget (JSX, RadioGroup, Automate, Chemistry widget...) designed for a general type of exercise.

**Comment by ddoyen** [comment]
Without component, how do we retrieve the audio file after recording ?

**Comment by mciissee** [comment]
[https://codeburst.io/html5-speech-recognition-api-670846a50e92](https://codeburst.io/html5-speech-recognition-api-670846a50e92)

**Comment by ddoyen** [comment]
I'm not sure to understand. What I call "audio recorder" is something that would provide an audio file (this file being then processed on the server side). 

Maybe it's not possible, but it seems to me that's something different from speech recognition. It's "speech to audio file" vs "speech to text". What am I missing ?

**Comment by mciissee** [comment]
SpeechRecognition API ask a user to speak and let the developer to get the textual transcription of the audio.

If you want to record an audio you can use HTML5 audio element which provides also this feature.
You can find and example at  [ https://developers.google.com/web/fundamentals/media/recording-audio](https://developers.google.com/web/fundamentals/media/recording-audio)

**Comment by mciissee** [comment]
If you want to use the JavaScript API only, you can look at [https://medium.com/@bryanjenningz/how-to-record-and-play-audio-in-javascript-faa1b2b3e49b](https://medium.com/@bryanjenningz/how-to-record-and-play-audio-in-javascript-faa1b2b3e49b).

Another issue with what you try to implement is that you cannot send non textual data to the grader even with a component

**Comment by ddoyen** [comment]
> Another issue with what you try to implement is that you cannot send non textual data to the grader even with a component

Ok. Now I understand the problem.
